[J-TB-0~28] 모집글쓰기 작성완료시 모집글뷰페이지로 이동 추가
peer-42seoul/Peer-Frontend pull request #201
Opened 2023-11-03 01:20 UTC by joonseong11

### 변경된점
- 모집글쓰기 작성완료시 만들어진 모집글 뷰로 이동합니다.
- 지난 풀리퀘에서 지적받은 요소들 반영 (useSWR적용, flex 대신 stack 사용 등)

### 필요사항
- 백엔드 API 와 연동이 잘 안되는 상황인데 체크가 필요합니다.

2023-11-03 02:11 UTC, SaltySalt77 requested changes
api가 연동이 잘 안된다고하셨는데, 엔드 포인트에 '/api/v1'이 없는 경우와 토큰이 필요한데 없는 경우가 많은 것 같습니다. 확인 부탁드립니다.

2023-11-03 02:11 UTC, SaltySalt77 commented on src/app/recruitment/[id]/edit/panel/SetTeamTag/TagAutoComplete.tsx
> +  const { data } = useSWR(`${process.env.NEXT_PUBLIC_API_URL}/recruit/write`, defaultGetFetcher)
여기도 엔드포인트가 다른 것 같은데 확인 부탁드립니다.
명세서 [링크](https://github.com/orgs/peer-42seoul/projects/35/views/1?pane=issue&itemId=40541713)

또한 토큰이 요구되는 api라고 명시되어 있는데, 토큰을 요구하는 경우 `defaultGetFetcher`대신 `getFetcherWithInstance`를 사용해야합니다.

2023-11-03 02:11 UTC, SaltySalt77 commented on src/app/recruitment/write/page.tsx
>  }
다른 파일에서는 @/types/IPostDetail에서 import해와서 쓰고있는데, 여기서는 선언을 해두셔서요. 통일이 필요할 것 같습니다.

2023-11-03 02:11 UTC, SaltySalt77 commented on src/app/recruitment/write/page.tsx
> +      .post(`${process.env.NEXT_PUBLIC_API_URL}/recruit/write`, {
여기도 엔드포인트가 다른 것 같습니다.
전체적으로 환경 변수 뒤에 `/api/v1`을 붙여주셔야 할 것 같아요

2023-11-03 02:11 UTC, SaltySalt77 commented on src/app/recruitment/write/page.tsx
>      await axios
명세서에는 토큰이 필요하다고 명시되어있는데, get 요청이 아닐 때에는 `useAxiosWithAuth` 훅으로 axiosInstance를 가져와 axios대신 사용하시면 됩니다.

2023-11-03 02:11 UTC, SaltySalt77 commented on src/app/recruitment/write/page.tsx
> +        router.push(`/recruitment/${res.data}`) // 백엔드에서 리턴값으로 새로생긴 모집글의 id 를 던져줌
body가 id만 주는 것으로 확정이 난 상태일까요?
명세서 업데이트 부탁드립니다~

2023-11-03 02:11 UTC, SaltySalt77 commented on src/app/recruitment/write/panel/SetTeamTag/TagAutoComplete.tsx
> +  const { data } = useSWR(`${process.env.NEXT_PUBLIC_API_URL}/recruit/write`, defaultGetFetcher)
여기도 엔드포인트 확인 부탁드립니다~
그리고 해당 api도 토큰 필요한데, fetcher 변경이 필요해보입니다.

2023-11-03 04:25 UTC, joonseong11 commented on src/app/recruitment/[id]/edit/page.tsx
> +  const {data} = useSWR(`${process.env.NEXT_PUBLIC_API_URL}/recruit/edit/recruit_id`, defaultGetFetcher)
다른 파트 분들과 Api 연계 작업후 바로 해결 할게용

2023-11-03 09:36 UTC, joonseong11 commented on src/app/recruitment/write/page.tsx
> +        router.push(`/recruitment/${res.data}`) // 백엔드에서 리턴값으로 새로생긴 모집글의 id 를 던져줌
업데이트완료~

2023-11-03 10:56 UTC, joonseong11 commented on src/app/recruitment/[id]/edit/panel/SetTeamTag/TagAutoComplete.tsx
> +  const { data } = useSWR(`${process.env.NEXT_PUBLIC_API_URL}/recruit/write`, defaultGetFetcher)
반영완료했습니당

2023-11-03 10:56 UTC, joonseong11 commented on src/app/recruitment/write/page.tsx
> +      .post(`${process.env.NEXT_PUBLIC_API_URL}/recruit/write`, {
넵 완료~

2023-11-03 11:07 UTC, joonseong11 commented on src/app/recruitment/write/panel/SetTeamTag/TagAutoComplete.tsx
> +  const { data } = useSWR(`${process.env.NEXT_PUBLIC_API_URL}/recruit/write`, defaultGetFetcher)
반영완료했습니당

2023-11-03 11:07 UTC, joonseong11 commented on src/app/recruitment/write/page.tsx
>      await axios
넵

2023-11-03 11:23 UTC, SaltySalt77 requested changes
코멘트 넣은 부분 확인해서 고쳐주시면 좋을 것 같습니다!

2023-11-03 11:23 UTC, SaltySalt77 commented on src/app/recruitment/[id]/edit/page.tsx
> +import { AxiosInstance } from 'axios'
저희 구현사항을 떠올려보면 import되면 안되는 객체입니다. 제거 부탁드려요

2023-11-03 11:23 UTC, SaltySalt77 commented on src/app/recruitment/[id]/edit/page.tsx
> +import { getFetcherWithInstance } from '@/api/fetchers'
디스코드 프론트 노티 확인 부탁드려요. useSWR에서 해당 fetcher를 쓰면 안됩니다.

2023-11-03 11:23 UTC, SaltySalt77 commented on src/app/recruitment/[id]/edit/page.tsx
> +const CreateTeam = ({ params }: { params: { recruit_id: string } }) => {
말씀드린거 바로 적용하셨군요~ 굿

2023-11-03 11:23 UTC, SaltySalt77 commented on src/app/recruitment/[id]/edit/page.tsx
> +  )
이렇게 하면 무한히 요청을 보내게 됩니다. 프론트 노티 확인해서 고쳐주세요~

2023-11-03 11:23 UTC, SaltySalt77 commented on src/app/recruitment/[id]/edit/page.tsx
> +      if (response.status === 200) router.push(`/recruitment/${response.data}`) // 백엔드에서 리턴값으로 새로생긴 모집글의 id 를 던져줌
promise와 예외처리에 대해서 잠시 이야기를 나누었습니다. 
클린 코드를 위해 리펙토링 방법은 두 가지가 있습니다.
1. try catch문을 없애고 프로미스로 처리한다.
2. if문을 제거한다.

2023-11-04 07:36 UTC, SaltySalt77 approved these changes
코멘트 확인해주세요~ 고생하셨습니다~

2023-11-04 07:36 UTC, SaltySalt77 commented on src/app/recruitment/[id]/edit/page.tsx
> +  )
요청드린대로 수정하셨네요 👍굿 좋습니다

2023-11-04 07:36 UTC, SaltySalt77 commented on src/app/recruitment/[id]/edit/panel/radioGroupStatus.tsx
> +        aria-labelledby="demo-row-radio-buttons-group-label"
aria-labllendby라는 속성은 해당 라디오 그룹에 대해, 어떤 label이 붙어있는지 알려주는 역할을 합니다. 따라서 해당 속성을 이용하기 위해서는 label에 id 속성을 통해 유니크 값을 배정하고, 해당 아이디를 aria-labelledby라는 속성에 같은 값을 넣어주면 됩니다. 자세한 내용은 이쪽을 확인해주세요~
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby

2023-11-04 10:09 UTC, KRimwoo approved these changes
문제없어 보입니다! LGTM~ 코멘트 부분만 한 번 확인해주시고 추후에 필요하면 수정해주세요~

2023-11-04 10:09 UTC, KRimwoo commented on src/app/recruitment/[id]/edit/page.tsx
> +      const response = await axiosInstance.post(
여기 요청 주소랑 post 메소드 쓰는게 맞나요? 백엔드 코드로는 recruit/${recruit_id}로 put요청이 맞는 것 같아서요!

2023-11-05 03:56 UTC, joonseong11 commented on src/app/recruitment/[id]/edit/page.tsx
> +      const response = await axiosInstance.post(
아하 이부부 잘못들어갔네요 바로 다음 pr에서 수정예정!

2023-11-05 03:56 UTC, joonseong11 commented on src/app/recruitment/[id]/edit/panel/radioGroupStatus.tsx
> +        aria-labelledby="demo-row-radio-buttons-group-label"
넵넵 다음 피알에서 수정예정입니당

2023-11-05 03:56 UTC, merged