[I-TM] 서버와의 연동작업과 타입 수정, 자잘한 버그 수정
peer-42seoul/Peer-Frontend pull request #280
Opened 2023-11-10 11:21 UTC by HiHoi

2023-11-10 12:07 UTC, SaltySalt77 requested changes
코멘트 확인하고 수정 부탁드립니다!

2023-11-10 13:41 UTC, HiHoi commented on src/app/teams/@setting/[id]/panel/SetupTeam.tsx
> +      region: [event.target.value, teamInfo.region[1], teamInfo.region[2]],
원래 기능이 있었지만 기획 변경으로 추후에 기능을 다시 넣을 수가 있어서 생긴 여백입니다.

2023-11-10 13:42 UTC, HiHoi commented on src/app/my-page/profile/page.tsx
> +            profileImageURL: userInfo.profileImageURL,
이 부분 수정했는데 push가 안되어 있네요 지금은 수정했습니다.

2023-11-11 08:18 UTC, SaltySalt77 approved these changes
요청드린 수정 사항 수정하신 것 확인했습니다!

2023-11-13 09:14 UTC, SaltySalt77 requested changes
form-data관련해서 코드를 수정해야 하는 부분이 좀 있는 것 같습니다.
코멘트 확인 부탁드립니다!

2023-11-13 09:14 UTC, SaltySalt77 commented on src/app/teams/@setting/[id]/panel/SetupTeam.tsx
> +        },
저도 form-data형식으로 요청 보내는 부분이 있던 것으로 기억하는데, 헤더 부분을 참고 해야할 것 같습니다.
다만 form-data는 본문 부분인데 header에 넣어도 되나요? 확인 부탁드립니다.

2023-11-13 09:14 UTC, SaltySalt77 commented on src/app/teams/@setting/[id]/panel/SetupTeam.tsx
> +        },
또한 form-data로 보내기 위해서는 FormData 객체를 사용해야 하는 것으로 알고있습니다. 이부분도 확인 부탁드려요!
[mdn FormData](https://developer.mozilla.org/ko/docs/Web/API/FormData)

2023-11-13 10:11 UTC, HiHoi commented on src/app/teams/@setting/[id]/panel/SetupTeam.tsx
> +        },
사실 요부분이 백엔드 요청으로 바꾼 부분인데 아직 서버까지 적용이 안된 거 같습니다. 그래서 테스트가 안된 부분이라 좀 더 테스트를 진행해서 완성지어 놓겠습니다. 또 보니 그냥 formdata 형태를 안맞춰준 모습이네요. 수정하겠습니다.

2023-11-13 13:01 UTC, joonseong11 approved these changes
타입 바꾸신것, axiosInstance 반영된 부분, 팀 설정페이지 개편사항 확인했습니다 고생많으셨습니다 잘봤습니다 ㅎㅎ

2023-11-13 13:01 UTC, joonseong11 commented on src/app/teams/@setting/[id]/panel/SetupTeam.tsx
> +    formdata.append('id', teamInfo.id)
아하 state로 다 들고있지 않아도 formdata로 들고있으면 되는군여. 컴포넌트에서 변동사항이 생겨 컴포넌트가 재 렌더링이 발생하면 const 로 선언된 변수들이 날라가거나 하지는 않죠?

2023-11-14 06:53 UTC, SaltySalt77 approved these changes
코드 수정 하긴 부분 잘 봤습니다. 굿!

2023-11-14 06:53 UTC, SaltySalt77 commented on src/app/teams/@setting/[id]/panel/SetupTeam.tsx
> +    formdata.append('id', teamInfo.id)
FormData로 저장을 해두는 게 아니라, multipart-formdata형식으로 body를 보내기 위해 설정하는 부분인 것 같습니다. 컴포넌트에 재 렌더링이 발생하면 (당연히) 다 날라갑니다.

2023-11-14 06:58 UTC, joonseong11 commented on src/app/teams/@setting/[id]/panel/SetupTeam.tsx
> +    formdata.append('id', teamInfo.id)
감사합니다 좋은 이해가 되었습니다~

2023-11-14 11:25 UTC, SaltySalt77 approved these changes
컨플릭트 해결하신 것 확인했습니다~

2023-11-14 11:48 UTC, joonseong11 approved these changes

2023-11-14 11:49 UTC, merged