Feat/messages
peer-42seoul/Peer-Frontend pull request #40
Opened 2023-09-12 08:31 UTC by asroq1

mock서버 만들어서 쪽지 기능 구현했습니다.

2023-09-12 08:43 UTC, hyeon81 reviewed
주스탠드를 쓰지 않아도 구현이 가능할 것 같습니다. 대규모 공사가 필요할 것 같으니 추후에 zustand를 사용하지 않는 방식으로 수정 부탁드립니다~

2023-09-12 08:43 UTC, hyeon81 commented on peer_web_frontend/src/components/MessageNavigator.tsx
> +          <path
svg는 public으로 빼도 좋지 않을까요? path가 너무 길어욥

2023-09-12 08:47 UTC, SaltySalt77 commented on peer_web_frontend/src/components/MessageList.tsx
> +        <img
mui Box를 활용해서 img 태그를 사용해주세요~

2023-09-12 08:52 UTC, SaltySalt77 requested changes
말씀드린 부분만 잘 수정하면 될 것 같습니다:)
1. useSWR 사용 시 !data로 체크하는 것이 아닌 isLoading 활용
2. 프로필의 Link 태그
3. img태그를 Box에 넣기

2023-09-13 08:29 UTC, SaltySalt77 submitted a review, later dismissed
LGTM!

2023-09-13 09:04 UTC, hyeon81 approved these changes
잘 반영해주셨네요! 따봉 드립니다.

2023-09-13 09:09 UTC, SaltySalt77 approved these changes
더 깔끔하게 된 것 같습니다. 굿~

2023-09-13 09:10 UTC, merged