[C-MAIN] 메인 페이지 목업서버 생성, SSR로 데이터 가져오기
peer-42seoul/Peer-Frontend pull request #65
Opened 2023-09-19 08:34 UTC by hyeon81

목업 서버를 생성했습니다.
SSR로 렌더링 되도록 리팩토링했습니다.
api/fetcher에 fetchServerData와 fetchStaticData를 만들었습니다.

2023-09-19 09:35 UTC, joonseong11 approved these changes
잘봤습니다~~

2023-09-20 06:06 UTC, asroq1 requested changes

2023-09-20 06:06 UTC, asroq1 commented on peer_web_frontend/src/app/panel/SelectSort.tsx
>  interface SelectSortProps {
인터페이스 앞에는 I 를 붙여주세요 !

2023-09-20 06:35 UTC, joonseong11 approved these changes
린트 적용하신 거 맞지유? 또 바뀐곳은 크게 없어보이는디...!

2023-09-20 06:58 UTC, asroq1 approved these changes
수정한다고 고생 많이 하셨습니다 ㅎㅎ NextJS 13 버전에서 발생하는 axios 이슈는 고민해볼 필요가 있겠네요 수고하셨습니다

2023-09-20 07:01 UTC, joonseong11 approved these changes
Axios I 타입명 확인했습니다~

2023-09-20 07:02 UTC, merged