Create public card, button, input
peer-42seoul/Peer-Frontend pull request #79
Opened 2023-09-26 07:20 UTC by HiHoi

임시 PR 입니다.

현재 작업물을 올립니다.

2023-09-26 07:27 UTC, SaltySalt77 requested changes
prop 인터페이스를 보니 모두 필수로 들어가있는데, style이나 TextField 같은 경우 react-form를 사용할 시 onChange를 따로 개발자기 넣지 않아서 필수 부분이 아니라면 선택적으로 프롭을 줄 수 있도록 처리가 되면 좋을 것 같습니다.
TextField 예시
```tsx
<Controller
  render={({ field }) => (
    <TextField
      label="자기 소개"
      variant="outlined"
      {...field}
      sx={{ width: '100%' }}
    />
  )}
  name="introduction"
  control={control}
/>
```

2023-09-28 07:00 UTC, HiHoi commented on peer_web_frontend/src/app/page.tsx
> +    'https://27366dd1-6e95-4ec6-90c2-062a85a79dfe.mock.pstmn.io/projects-sort-recent',
포스트맨 목업 서버 URL 입니다.

2023-09-28 07:01 UTC, HiHoi commented on peer_web_frontend/src/app/panel/Header.tsx
> +      </Box>
기존 header의 무게를 줄이기 위해 검색 모달에서 사용될 헤더를 합쳐서 보여주는 형태로 바꿨습니다.

2023-10-02 10:13 UTC, SaltySalt77 commented on peer_web_frontend/src/hook/useMedia.tsx
> +export default useMedia
이거 좋은 것 같아요!

2023-10-02 10:13 UTC, SaltySalt77 approved these changes
굿! useMedia의 isPC 잘쓰겠습니다

2023-10-02 11:43 UTC, KRimwoo approved these changes
공용 컴포넌트 좋습니다~!!

2023-10-02 11:59 UTC, merged