[B-INFO] 회원가입 페이지에서 안쓰는 필드 삭제
peer-42seoul/Peer-Frontend pull request #84
Opened 2023-09-26 08:39 UTC by heehoh

- 회원가입 페이지에서 안쓰는 필드를 삭제했습니다.
- 서버에 axios 이메일 인증, 인증코드, 닉네임 중복 확인 로직 작성했습니다.

2023-09-26 10:16 UTC, SaltySalt77 requested changes
이메일 부분 구현과 비밀번호 유효성 검사만 잘 처리하면 될 것 같습니다!

2023-09-26 17:43 UTC, KRimwoo submitted a review, later dismissed
비밀번호 유효성 검증 과정이 조금 어려워진 걸로 알고있는데 화이팅입니다!

2023-10-04 08:34 UTC, KRimwoo submitted a review, later dismissed
오 훨씬 깔끔해진 것 같네요! 좋습니다~

2023-10-04 08:35 UTC, SaltySalt77 reviewed
코멘트 확인해주세요!

2023-10-04 08:35 UTC, SaltySalt77 commented on peer_web_frontend/src/types/ISignUpInputs.ts
> +  passwordConfirm: string
<img width="341" alt="스크린샷 2023-10-04 오후 5 27 20" src="https://github.com/peer-42seoul/Peer-Frontend/assets/91731260/a0c3a6cb-c138-4fcc-9257-a695a64b8d0c">
<br>
비밀번호 확인란을 넣는 대신 비밀번호 보기 버튼이 들어가는 것으로 결정되었습니다. 확인해주세요!

2023-10-06 08:41 UTC, SaltySalt77 approved these changes
잘 확인했습니다!!

2023-10-06 08:41 UTC, SaltySalt77 commented on peer_web_frontend/src/app/signup/panel/SignUpField.tsx
> +              }}
닉네임 중복확인 버튼을 어떻게 넣을 지 고민하고 있었는데, 이렇게 넣으면 될 것 같네요! 참고하겠습니다!

2023-10-08 04:42 UTC, KRimwoo approved these changes
이제 api연결만하면 되겠네요~ 굿!!

2023-10-08 15:33 UTC, merged