[C-SRC] 검색 로직 변경
peer-42seoul/Peer-Frontend pull request #93
Opened 2023-10-04 06:25 UTC by HiHoi

기존 검색창에서 api를 사용해서 검색 데이터를 불러오는 구조에서 메인에 키워드를 전달하고 메인에서 다시 api를 사용하는 걸로 변경

2023-10-04 08:42 UTC, asroq1 approved these changes
LGTM !

2023-10-04 09:35 UTC, SaltySalt77 requested changes

2023-10-04 09:35 UTC, SaltySalt77 commented on peer_web_frontend/src/app/search/panel/SearchBody.tsx
placeholder의 문구 조건에 `type`만 들어가있는데, 잘못 비교가 된 것 같습니다. 이 부분 수정이 필요할 것 같아요!

2023-10-05 03:17 UTC, HiHoi commented on peer_web_frontend/src/app/search/panel/SearchBody.tsx
수정했습니다 확인해주세요!

2023-10-06 05:44 UTC, SaltySalt77 approved these changes
수정 요청드린 부분 수정한 것 확인했습니다!

2023-10-06 05:45 UTC, asroq1 approved these changes

2023-10-06 05:45 UTC, merged